# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://hoangthienan95.github.io/combinatorial_GWAS/"

git_url = "https://github.com/hoangthienan95/combinatorial_GWAS/tree/master/"

def custom_doc_links(name): return None
