# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"parameters": "phenotypes.ipynb",
         "DelegatedAttribute": "Field.ipynb",
         "delegate_as": "Field.ipynb",
         "Field": "Field.ipynb",
         "DictLine": "Field.ipynb",
         "Coding": "Field.ipynb",
         "cd": "catalog.ipynb",
         "change_cwd_dir": "catalog.ipynb",
         "get_config": "catalog.ipynb",
         "get_catalog": "catalog.ipynb",
         "get_parameters": "catalog.ipynb",
         "reload_catalog": "catalog.ipynb",
         "reload": "catalog.ipynb",
         "package_outer_folder": "catalog.ipynb",
         "get_geno_one_snp": "genotype.ipynb",
         "BgenFileObject": "genotype.ipynb",
         "get_genetic_file_path": "genotype.ipynb",
         "load_genetic_file": "genotype.ipynb",
         "QueryDataframe": "phenotypes.ipynb",
         "catalog_all": "phenotypes.ipynb",
         "read_csv_compressed": "phenotypes.ipynb",
         "get_GWAS_result_link": "phenotypes.ipynb",
         "icd10_pheno_matrix": "phenotypes.ipynb",
         "icd10_primary_cols": "phenotypes.ipynb",
         "get_phenotype": "phenotypes.ipynb",
         "get_GWAS_snps_for_trait": "phenotypes.ipynb"}

modules = ["phenotypes/Field.py",
           "data_catalog.py",
           "genotype.py",
           "phenotypes/__init__.py"]

doc_url = "https://hoangthienan95.github.io/combinatorial_GWAS/"

git_url = "https://github.com/hoangthienan95/combinatorial_gwas/tree/master/"

def custom_doc_links(name): return None
